# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bob's Creative Software Solutions
email: robertgweilbaecher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Started on January 1st, 2014 to find solutions to complex problems ranging from the integration of healthcare and technology to creating calendars to set up a training regimen for an upcomming marathon.
baseurl: "/bobs-creative-software-solutions/" # the subpath of your site, e.g. /blog
url: "http://sahedeva.github.io" # the base hostname & protocol for your site
twitter_username: robertweilbaec1
github_username:  Sahedeva

# Build settings
markdown: kramdown
